-- CreateTable
CREATE TABLE `Toilet` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `operatingHours` VARCHAR(200) NULL,
    `maleToilets` INTEGER NOT NULL DEFAULT 0,
    `maleUrinals` INTEGER NOT NULL DEFAULT 0,
    `femaleToilets` INTEGER NOT NULL DEFAULT 0,
    `hasDisabledToilet` BOOLEAN NOT NULL DEFAULT false,
    `openTime` VARCHAR(100) NULL,
    `managingOrg` VARCHAR(200) NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `installDate` VARCHAR(50) NULL,
    `ownershipType` VARCHAR(50) NULL,
    `sewageTreatment` VARCHAR(100) NULL,
    `hasEmergencyBell` BOOLEAN NOT NULL DEFAULT false,
    `emergencyBellLocation` VARCHAR(200) NULL,
    `hasCCTV` BOOLEAN NOT NULL DEFAULT false,
    `hasDiaperChangingTable` BOOLEAN NOT NULL DEFAULT false,
    `diaperChangingLocation` VARCHAR(200) NULL,
    `maleDisabledToilets` INTEGER NOT NULL DEFAULT 0,
    `maleDisabledUrinals` INTEGER NOT NULL DEFAULT 0,
    `maleChildToilets` INTEGER NOT NULL DEFAULT 0,
    `maleChildUrinals` INTEGER NOT NULL DEFAULT 0,
    `femaleDisabledToilets` INTEGER NOT NULL DEFAULT 0,
    `femaleChildToilets` INTEGER NOT NULL DEFAULT 0,
    `remodelingDate` VARCHAR(50) NULL,
    `facilityType` VARCHAR(100) NULL,
    `legalBasis` VARCHAR(200) NULL,
    `govCode` VARCHAR(20) NULL,
    `dataDate` VARCHAR(20) NULL,

    UNIQUE INDEX `Toilet_sourceId_key`(`sourceId`),
    INDEX `Toilet_city_district_idx`(`city`, `district`),
    INDEX `Toilet_lat_lng_idx`(`lat`, `lng`),
    INDEX `Toilet_bjdCode_idx`(`bjdCode`),
    INDEX `Toilet_viewCount_idx`(`viewCount`),
    INDEX `Toilet_name_idx`(`name`),
    FULLTEXT INDEX `Toilet_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Wifi` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `ssid` VARCHAR(100) NULL,
    `installDate` VARCHAR(50) NULL,
    `serviceProvider` VARCHAR(100) NULL,
    `installLocation` VARCHAR(200) NULL,
    `managementAgency` VARCHAR(200) NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `installLocationDetail` VARCHAR(500) NULL,
    `govCode` VARCHAR(20) NULL,
    `dataDate` VARCHAR(20) NULL,
    `groupId` VARCHAR(24) NULL,

    UNIQUE INDEX `Wifi_sourceId_key`(`sourceId`),
    INDEX `Wifi_city_district_idx`(`city`, `district`),
    INDEX `Wifi_lat_lng_idx`(`lat`, `lng`),
    INDEX `Wifi_bjdCode_idx`(`bjdCode`),
    INDEX `Wifi_viewCount_idx`(`viewCount`),
    INDEX `Wifi_name_idx`(`name`),
    INDEX `Wifi_groupId_idx`(`groupId`),
    FULLTEXT INDEX `Wifi_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Clothes` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `managementAgency` VARCHAR(200) NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `dataDate` VARCHAR(50) NULL,
    `detailLocation` VARCHAR(500) NULL,
    `providerCode` VARCHAR(20) NULL,
    `providerName` VARCHAR(200) NULL,

    UNIQUE INDEX `Clothes_sourceId_key`(`sourceId`),
    INDEX `Clothes_city_district_idx`(`city`, `district`),
    INDEX `Clothes_lat_lng_idx`(`lat`, `lng`),
    INDEX `Clothes_bjdCode_idx`(`bjdCode`),
    INDEX `Clothes_viewCount_idx`(`viewCount`),
    INDEX `Clothes_name_idx`(`name`),
    FULLTEXT INDEX `Clothes_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Park` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(200) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `parkType` VARCHAR(100) NULL,
    `area` DECIMAL(10, 2) NULL,
    `exerciseFacilities` TEXT NULL,
    `playFacilities` TEXT NULL,
    `convenienceFacilities` TEXT NULL,
    `cultureFacilities` TEXT NULL,
    `otherFacilities` TEXT NULL,
    `designatedDate` VARCHAR(50) NULL,
    `managingOrg` VARCHAR(200) NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `dataDate` VARCHAR(20) NULL,
    `providerCode` VARCHAR(20) NULL,
    `providerName` VARCHAR(200) NULL,

    UNIQUE INDEX `Park_sourceId_key`(`sourceId`),
    INDEX `Park_city_district_idx`(`city`, `district`),
    INDEX `Park_lat_lng_idx`(`lat`, `lng`),
    INDEX `Park_bjdCode_idx`(`bjdCode`),
    INDEX `Park_viewCount_idx`(`viewCount`),
    INDEX `Park_name_idx`(`name`),
    FULLTEXT INDEX `Park_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `School` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `geocodedAddress` VARCHAR(500) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(200) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `schoolLevel` VARCHAR(50) NULL,
    `foundedDate` VARCHAR(20) NULL,
    `foundationType` VARCHAR(50) NULL,
    `branchType` VARCHAR(20) NULL,
    `operationStatus` VARCHAR(20) NULL,
    `sidoEduCode` VARCHAR(20) NULL,
    `sidoEduName` VARCHAR(100) NULL,
    `localEduCode` VARCHAR(20) NULL,
    `localEduName` VARCHAR(100) NULL,
    `createdDate` VARCHAR(20) NULL,
    `modifiedDate` VARCHAR(20) NULL,
    `dataDate` VARCHAR(20) NULL,
    `providerCode` VARCHAR(20) NULL,
    `providerName` VARCHAR(200) NULL,
    `neisSchoolCode` VARCHAR(20) NULL,
    `neisEduCode` VARCHAR(10) NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `faxNumber` VARCHAR(50) NULL,
    `homepageUrl` VARCHAR(500) NULL,
    `coeducationType` VARCHAR(20) NULL,
    `highSchoolType` VARCHAR(50) NULL,
    `dayNightType` VARCHAR(10) NULL,

    UNIQUE INDEX `School_sourceId_key`(`sourceId`),
    INDEX `School_city_district_idx`(`city`, `district`),
    INDEX `School_lat_lng_idx`(`lat`, `lng`),
    INDEX `School_bjdCode_idx`(`bjdCode`),
    INDEX `School_schoolLevel_idx`(`schoolLevel`),
    INDEX `School_viewCount_idx`(`viewCount`),
    INDEX `School_name_idx`(`name`),
    FULLTEXT INDEX `School_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SchoolEnrollment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `schoolId` VARCHAR(50) NOT NULL,
    `year` INTEGER NOT NULL,
    `grade` INTEGER NOT NULL,
    `classCount` INTEGER NULL,

    INDEX `SchoolEnrollment_schoolId_idx`(`schoolId`),
    UNIQUE INDEX `SchoolEnrollment_schoolId_year_grade_key`(`schoolId`, `year`, `grade`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SchoolDepartment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `schoolId` VARCHAR(50) NOT NULL,
    `departmentName` VARCHAR(100) NOT NULL,

    INDEX `SchoolDepartment_schoolId_idx`(`schoolId`),
    UNIQUE INDEX `SchoolDepartment_schoolId_departmentName_key`(`schoolId`, `departmentName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Childcare` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `crtypename` VARCHAR(100) NULL,
    `crstatusname` VARCHAR(50) NULL,
    `zipcode` VARCHAR(10) NULL,
    `crtelno` VARCHAR(50) NULL,
    `crfaxno` VARCHAR(50) NULL,
    `crhome` VARCHAR(500) NULL,
    `crrepname` VARCHAR(100) NULL,
    `nrtrroomcnt` INTEGER NULL,
    `nrtrroomsize` VARCHAR(50) NULL,
    `plgrdco` INTEGER NULL,
    `cctvinstlcnt` INTEGER NULL,
    `chcrtescnt` INTEGER NULL,
    `crcapat` INTEGER NULL,
    `crchcnt` INTEGER NULL,
    `crcargbname` VARCHAR(100) NULL,
    `crcnfmdt` VARCHAR(20) NULL,
    `crpausebegindt` VARCHAR(20) NULL,
    `crpauseenddt` VARCHAR(20) NULL,
    `crabldt` VARCHAR(20) NULL,
    `datastdrdt` VARCHAR(20) NULL,
    `crspec` TEXT NULL,
    `classCnt00` INTEGER NULL,
    `classCnt01` INTEGER NULL,
    `classCnt02` INTEGER NULL,
    `classCnt03` INTEGER NULL,
    `classCnt04` INTEGER NULL,
    `classCnt05` INTEGER NULL,
    `classCntM2` INTEGER NULL,
    `classCntM5` INTEGER NULL,
    `classCntSp` INTEGER NULL,
    `classCntTot` INTEGER NULL,
    `childCnt00` INTEGER NULL,
    `childCnt01` INTEGER NULL,
    `childCnt02` INTEGER NULL,
    `childCnt03` INTEGER NULL,
    `childCnt04` INTEGER NULL,
    `childCnt05` INTEGER NULL,
    `childCntM2` INTEGER NULL,
    `childCntM5` INTEGER NULL,
    `childCntSp` INTEGER NULL,
    `childCntTot` INTEGER NULL,
    `emCnt0y` INTEGER NULL,
    `emCnt1y` INTEGER NULL,
    `emCnt2y` INTEGER NULL,
    `emCnt4y` INTEGER NULL,
    `emCnt6y` INTEGER NULL,
    `emCntA1` INTEGER NULL,
    `emCntA2` INTEGER NULL,
    `emCntA3` INTEGER NULL,
    `emCntA4` INTEGER NULL,
    `emCntA5` INTEGER NULL,
    `emCntA6` INTEGER NULL,
    `emCntA10` INTEGER NULL,
    `emCntA7` INTEGER NULL,
    `emCntA8` INTEGER NULL,
    `emCntTot` INTEGER NULL,
    `ewCnt00` INTEGER NULL,
    `ewCnt01` INTEGER NULL,
    `ewCnt02` INTEGER NULL,
    `ewCnt03` INTEGER NULL,
    `ewCnt04` INTEGER NULL,
    `ewCnt05` INTEGER NULL,
    `ewCntM6` INTEGER NULL,
    `ewCntTot` INTEGER NULL,

    UNIQUE INDEX `Childcare_sourceId_key`(`sourceId`),
    INDEX `Childcare_city_district_idx`(`city`, `district`),
    INDEX `Childcare_lat_lng_idx`(`lat`, `lng`),
    INDEX `Childcare_bjdCode_idx`(`bjdCode`),
    INDEX `Childcare_crtypename_idx`(`crtypename`),
    INDEX `Childcare_viewCount_idx`(`viewCount`),
    INDEX `Childcare_name_idx`(`name`),
    FULLTEXT INDEX `Childcare_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Market` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `marketType` VARCHAR(50) NULL,
    `openingCycle` VARCHAR(100) NULL,
    `storeCount` INTEGER NULL,
    `products` TEXT NULL,
    `giftCertificates` TEXT NULL,
    `homepageUrl` VARCHAR(500) NULL,
    `hasPublicToilet` BOOLEAN NULL,
    `hasParking` BOOLEAN NULL,
    `foundedYear` INTEGER NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `dataDate` VARCHAR(20) NULL,
    `providerCode` VARCHAR(20) NULL,
    `providerName` VARCHAR(200) NULL,

    UNIQUE INDEX `Market_sourceId_key`(`sourceId`),
    INDEX `Market_city_district_idx`(`city`, `district`),
    INDEX `Market_lat_lng_idx`(`lat`, `lng`),
    INDEX `Market_bjdCode_idx`(`bjdCode`),
    INDEX `Market_viewCount_idx`(`viewCount`),
    INDEX `Market_name_idx`(`name`),
    FULLTEXT INDEX `Market_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Parking` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `parkingType` VARCHAR(50) NULL,
    `lotType` VARCHAR(50) NULL,
    `capacity` INTEGER NOT NULL DEFAULT 0,
    `baseFee` INTEGER NULL,
    `baseTime` INTEGER NULL,
    `additionalFee` INTEGER NULL,
    `additionalTime` INTEGER NULL,
    `dailyMaxFee` INTEGER NULL,
    `monthlyFee` INTEGER NULL,
    `operatingHours` VARCHAR(200) NULL,
    `phone` VARCHAR(50) NULL,
    `paymentMethod` VARCHAR(200) NULL,
    `remarks` TEXT NULL,
    `hasDisabledParking` BOOLEAN NOT NULL DEFAULT false,
    `zoneClass` VARCHAR(50) NULL,
    `alternateParking` VARCHAR(50) NULL,
    `operatingDays` VARCHAR(100) NULL,
    `feeType` VARCHAR(50) NULL,
    `dailyMaxFeeHours` VARCHAR(50) NULL,
    `managingOrg` VARCHAR(200) NULL,
    `dataDate` VARCHAR(20) NULL,
    `providerCode` VARCHAR(20) NULL,
    `providerName` VARCHAR(200) NULL,

    UNIQUE INDEX `Parking_sourceId_key`(`sourceId`),
    INDEX `Parking_city_district_idx`(`city`, `district`),
    INDEX `Parking_lat_lng_idx`(`lat`, `lng`),
    INDEX `Parking_bjdCode_idx`(`bjdCode`),
    INDEX `Parking_viewCount_idx`(`viewCount`),
    INDEX `Parking_name_idx`(`name`),
    FULLTEXT INDEX `Parking_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Aed` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `buildPlace` VARCHAR(500) NULL,
    `org` VARCHAR(200) NULL,
    `clerkTel` VARCHAR(50) NULL,
    `mfg` VARCHAR(100) NULL,
    `model` VARCHAR(100) NULL,
    `monSttTme` VARCHAR(4) NULL,
    `monEndTme` VARCHAR(4) NULL,
    `tueSttTme` VARCHAR(4) NULL,
    `tueEndTme` VARCHAR(4) NULL,
    `wedSttTme` VARCHAR(4) NULL,
    `wedEndTme` VARCHAR(4) NULL,
    `thuSttTme` VARCHAR(4) NULL,
    `thuEndTme` VARCHAR(4) NULL,
    `friSttTme` VARCHAR(4) NULL,
    `friEndTme` VARCHAR(4) NULL,
    `satSttTme` VARCHAR(4) NULL,
    `satEndTme` VARCHAR(4) NULL,
    `sunSttTme` VARCHAR(4) NULL,
    `sunEndTme` VARCHAR(4) NULL,
    `holSttTme` VARCHAR(4) NULL,
    `holEndTme` VARCHAR(4) NULL,
    `dataDate` VARCHAR(20) NULL,

    UNIQUE INDEX `Aed_sourceId_key`(`sourceId`),
    INDEX `Aed_city_district_idx`(`city`, `district`),
    INDEX `Aed_lat_lng_idx`(`lat`, `lng`),
    INDEX `Aed_bjdCode_idx`(`bjdCode`),
    INDEX `Aed_viewCount_idx`(`viewCount`),
    INDEX `Aed_name_idx`(`name`),
    FULLTEXT INDEX `Aed_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Library` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `libraryType` VARCHAR(50) NULL,
    `closedDays` VARCHAR(200) NULL,
    `weekdayOpenTime` VARCHAR(10) NULL,
    `weekdayCloseTime` VARCHAR(10) NULL,
    `saturdayOpenTime` VARCHAR(10) NULL,
    `saturdayCloseTime` VARCHAR(10) NULL,
    `holidayOpenTime` VARCHAR(10) NULL,
    `holidayCloseTime` VARCHAR(10) NULL,
    `seatCount` INTEGER NOT NULL DEFAULT 0,
    `bookCount` INTEGER NOT NULL DEFAULT 0,
    `serialCount` INTEGER NOT NULL DEFAULT 0,
    `nonBookCount` INTEGER NOT NULL DEFAULT 0,
    `loanableBooks` INTEGER NOT NULL DEFAULT 0,
    `loanableDays` INTEGER NOT NULL DEFAULT 0,
    `phoneNumber` VARCHAR(50) NULL,
    `homepageUrl` VARCHAR(500) NULL,
    `operatingOrg` VARCHAR(200) NULL,
    `lotArea` VARCHAR(50) NULL,
    `buildingArea` VARCHAR(50) NULL,
    `dataDate` VARCHAR(20) NULL,
    `providerCode` VARCHAR(20) NULL,
    `providerName` VARCHAR(200) NULL,

    UNIQUE INDEX `Library_sourceId_key`(`sourceId`),
    INDEX `Library_city_district_idx`(`city`, `district`),
    INDEX `Library_lat_lng_idx`(`lat`, `lng`),
    INDEX `Library_bjdCode_idx`(`bjdCode`),
    INDEX `Library_viewCount_idx`(`viewCount`),
    INDEX `Library_name_idx`(`name`),
    FULLTEXT INDEX `Library_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EvCharger` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `statId` VARCHAR(100) NULL,
    `chgerId` VARCHAR(50) NULL,
    `chgerType` VARCHAR(10) NULL,
    `addrDetail` VARCHAR(500) NULL,
    `location` VARCHAR(500) NULL,
    `useTime` VARCHAR(200) NULL,
    `busiId` VARCHAR(50) NULL,
    `bnm` VARCHAR(100) NULL,
    `busiNm` VARCHAR(200) NULL,
    `busiCall` VARCHAR(50) NULL,
    `stat` VARCHAR(5) NULL,
    `statUpdDt` VARCHAR(20) NULL,
    `lastTsdt` VARCHAR(20) NULL,
    `lastTedt` VARCHAR(20) NULL,
    `nowTsdt` VARCHAR(20) NULL,
    `powerType` VARCHAR(10) NULL,
    `output` VARCHAR(20) NULL,
    `method` VARCHAR(100) NULL,
    `zcode` VARCHAR(10) NULL,
    `zscode` VARCHAR(10) NULL,
    `kind` VARCHAR(10) NULL,
    `kindDetail` VARCHAR(10) NULL,
    `parkingFree` VARCHAR(1) NULL,
    `note` TEXT NULL,
    `limitYn` VARCHAR(1) NULL,
    `limitDetail` VARCHAR(500) NULL,
    `delYn` VARCHAR(1) NULL,
    `delDetail` VARCHAR(500) NULL,
    `trafficYn` VARCHAR(1) NULL,
    `year` VARCHAR(4) NULL,
    `floorNum` VARCHAR(50) NULL,
    `floorType` VARCHAR(1) NULL,
    `maker` VARCHAR(100) NULL,

    UNIQUE INDEX `EvCharger_sourceId_key`(`sourceId`),
    INDEX `EvCharger_city_district_idx`(`city`, `district`),
    INDEX `EvCharger_lat_lng_idx`(`lat`, `lng`),
    INDEX `EvCharger_bjdCode_idx`(`bjdCode`),
    INDEX `EvCharger_chgerType_idx`(`chgerType`),
    INDEX `EvCharger_statId_idx`(`statId`),
    INDEX `EvCharger_statId_city_district_idx`(`statId`, `city`, `district`),
    INDEX `EvCharger_city_district_statId_idx`(`city`, `district`, `statId`),
    INDEX `EvCharger_viewCount_idx`(`viewCount`),
    INDEX `EvCharger_name_idx`(`name`),
    FULLTEXT INDEX `EvCharger_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Sports` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `faciGbNm` VARCHAR(50) NULL,
    `fcobNm` VARCHAR(100) NULL,
    `ftypeNm` VARCHAR(100) NULL,
    `fmngCpNm` VARCHAR(100) NULL,
    `fmngCpbNm` VARCHAR(100) NULL,
    `faciGfa` DECIMAL(15, 2) NULL,
    `standCptPsnCnt` INTEGER NULL,
    `faciHomepage` VARCHAR(500) NULL,
    `faciStatCd` VARCHAR(10) NULL,
    `addrCtpvNm` VARCHAR(50) NULL,
    `addrCpbNm` VARCHAR(50) NULL,
    `addrEmdNm` VARCHAR(100) NULL,
    `nationYn` VARCHAR(1) NULL,
    `fmngTypeGbNm` VARCHAR(100) NULL,
    `delYn` VARCHAR(1) NULL,
    `rowNum` INTEGER NULL,

    UNIQUE INDEX `Sports_sourceId_key`(`sourceId`),
    INDEX `Sports_city_district_idx`(`city`, `district`),
    INDEX `Sports_lat_lng_idx`(`lat`, `lng`),
    INDEX `Sports_bjdCode_idx`(`bjdCode`),
    INDEX `Sports_ftypeNm_idx`(`ftypeNm`),
    INDEX `Sports_viewCount_idx`(`viewCount`),
    INDEX `Sports_name_idx`(`name`),
    FULLTEXT INDEX `Sports_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Category` (
    `id` VARCHAR(20) NOT NULL,
    `name` VARCHAR(50) NOT NULL,
    `icon` VARCHAR(10) NOT NULL,
    `description` VARCHAR(200) NULL,
    `sortOrder` INTEGER NOT NULL DEFAULT 0,
    `isActive` BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Region` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bjdCode` VARCHAR(5) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `slug` VARCHAR(50) NOT NULL,
    `lat` DECIMAL(10, 7) NOT NULL,
    `lng` DECIMAL(10, 7) NOT NULL,

    UNIQUE INDEX `Region_bjdCode_key`(`bjdCode`),
    UNIQUE INDEX `Region_city_district_key`(`city`, `district`),
    UNIQUE INDEX `Region_city_slug_key`(`city`, `slug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SearchLog` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `sessionId` VARCHAR(32) NOT NULL,
    `keyword` VARCHAR(200) NULL,
    `category` VARCHAR(20) NULL,
    `city` VARCHAR(50) NULL,
    `district` VARCHAR(50) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `resultCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `SearchLog_createdAt_idx`(`createdAt`),
    INDEX `SearchLog_keyword_idx`(`keyword`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SyncHistory` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `category` VARCHAR(20) NOT NULL,
    `status` ENUM('running', 'success', 'failed') NOT NULL,
    `totalRecords` INTEGER NOT NULL DEFAULT 0,
    `newRecords` INTEGER NOT NULL DEFAULT 0,
    `updatedRecords` INTEGER NOT NULL DEFAULT 0,
    `errorMessage` TEXT NULL,
    `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `completedAt` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Guide` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `slug` VARCHAR(200) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `summary` VARCHAR(500) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `articleType` VARCHAR(20) NOT NULL DEFAULT 'news',
    `thumbnailUrl` VARCHAR(500) NULL,
    `keywords` VARCHAR(500) NULL,
    `published` BOOLEAN NOT NULL DEFAULT true,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `publishedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Guide_slug_key`(`slug`),
    INDEX `Guide_category_idx`(`category`),
    INDEX `Guide_published_createdAt_idx`(`published`, `createdAt`),
    INDEX `Guide_slug_idx`(`slug`),
    INDEX `Guide_articleType_category_idx`(`articleType`, `category`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Article` (
    `id` VARCHAR(191) NOT NULL,
    `title` VARCHAR(200) NOT NULL,
    `slug` VARCHAR(200) NOT NULL,
    `content` LONGTEXT NOT NULL,
    `summary` VARCHAR(500) NOT NULL,
    `category` VARCHAR(50) NOT NULL,
    `articleType` VARCHAR(20) NOT NULL DEFAULT 'news-brief',
    `thumbnailUrl` VARCHAR(500) NULL,
    `keywords` VARCHAR(500) NULL,
    `sources` JSON NULL,
    `sourceExternalId` VARCHAR(100) NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'draft',
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `publishedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Article_slug_key`(`slug`),
    INDEX `Article_status_publishedAt_idx`(`status`, `publishedAt`),
    INDEX `Article_category_idx`(`category`),
    INDEX `Article_slug_idx`(`slug`),
    INDEX `Article_articleType_idx`(`articleType`),
    INDEX `Article_sourceExternalId_idx`(`sourceExternalId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AdminSession` (
    `id` VARCHAR(64) NOT NULL,
    `expiresAt` DATETIME(3) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `AdminSession_expiresAt_idx`(`expiresAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AdminLoginThrottle` (
    `id` VARCHAR(20) NOT NULL,
    `failedAttempts` INTEGER NOT NULL DEFAULT 0,
    `lockedUntil` DATETIME(3) NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ArticleGenerationLock` (
    `id` VARCHAR(20) NOT NULL,
    `running` BOOLEAN NOT NULL DEFAULT false,
    `startedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SubwayStation` (
    `id` VARCHAR(80) NOT NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `nameSlug` VARCHAR(150) NOT NULL,
    `line` VARCHAR(50) NOT NULL,
    `transferLines` TEXT NULL,
    `operator` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NOT NULL,
    `lng` DECIMAL(10, 7) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `city` VARCHAR(50) NULL,
    `district` VARCHAR(50) NULL,
    `regionSlug` VARCHAR(80) NULL,
    `phoneNumber` VARCHAR(50) NULL,
    `dataDate` VARCHAR(20) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `SubwayStation_sourceId_key`(`sourceId`),
    INDEX `SubwayStation_line_idx`(`line`),
    INDEX `SubwayStation_city_district_idx`(`city`, `district`),
    INDEX `SubwayStation_lat_idx`(`lat`),
    INDEX `SubwayStation_lng_idx`(`lng`),
    UNIQUE INDEX `SubwayStation_nameSlug_key`(`nameSlug`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `WasteSchedule` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `targetRegion` TEXT NULL,
    `emissionPlace` VARCHAR(100) NULL,
    `details` JSON NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `govCode` VARCHAR(20) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `WasteSchedule_city_district_idx`(`city`, `district`),
    UNIQUE INDEX `WasteSchedule_city_district_sourceId_key`(`city`, `district`, `sourceId`),
    FULLTEXT INDEX `WasteSchedule_targetRegion_emissionPlace_idx`(`targetRegion`, `emissionPlace`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Hospital` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `phone` VARCHAR(50) NULL,
    `homepage` VARCHAR(500) NULL,
    `postNo` VARCHAR(20) NULL,
    `estbDd` VARCHAR(20) NULL,
    `ykiho` VARCHAR(100) NULL,
    `clCd` VARCHAR(20) NULL,
    `clCdNm` VARCHAR(100) NULL,
    `sidoCd` VARCHAR(20) NULL,
    `sgguCd` VARCHAR(20) NULL,
    `emdongNm` VARCHAR(100) NULL,
    `drTotCnt` INTEGER NULL,
    `mdeptSdrCnt` INTEGER NULL,
    `mdeptGdrCnt` INTEGER NULL,
    `mdeptIntnCnt` INTEGER NULL,
    `mdeptResdntCnt` INTEGER NULL,
    `detySdrCnt` INTEGER NULL,
    `detyGdrCnt` INTEGER NULL,
    `detyIntnCnt` INTEGER NULL,
    `detyResdntCnt` INTEGER NULL,
    `cmdcSdrCnt` INTEGER NULL,
    `cmdcGdrCnt` INTEGER NULL,
    `cmdcIntnCnt` INTEGER NULL,
    `cmdcResdntCnt` INTEGER NULL,
    `pnursCnt` INTEGER NULL,
    `dataDate` VARCHAR(20) NULL,
    `trmtMonStart` VARCHAR(10) NULL,
    `trmtMonEnd` VARCHAR(10) NULL,
    `trmtTueStart` VARCHAR(10) NULL,
    `trmtTueEnd` VARCHAR(10) NULL,
    `trmtWedStart` VARCHAR(10) NULL,
    `trmtWedEnd` VARCHAR(10) NULL,
    `trmtThuStart` VARCHAR(10) NULL,
    `trmtThuEnd` VARCHAR(10) NULL,
    `trmtFriStart` VARCHAR(10) NULL,
    `trmtFriEnd` VARCHAR(10) NULL,
    `trmtSatStart` VARCHAR(10) NULL,
    `trmtSatEnd` VARCHAR(10) NULL,
    `trmtSunStart` VARCHAR(10) NULL,
    `trmtSunEnd` VARCHAR(10) NULL,
    `lunchWeek` VARCHAR(200) NULL,
    `lunchSat` VARCHAR(200) NULL,
    `noTrmtSun` VARCHAR(200) NULL,
    `noTrmtHoli` VARCHAR(200) NULL,
    `parkQty` INTEGER NULL,
    `parkEtc` VARCHAR(500) NULL,
    `detailSyncedAt` DATETIME(3) NULL,
    `foundationCd` VARCHAR(20) NULL,
    `foundationCdNm` VARCHAR(50) NULL,
    `generalUpperBeds` INTEGER NULL,
    `generalNormalBeds` INTEGER NULL,
    `adultIcuBeds` INTEGER NULL,
    `childIcuBeds` INTEGER NULL,
    `neonatalIcuBeds` INTEGER NULL,
    `deliveryBeds` INTEGER NULL,
    `operatingBeds` INTEGER NULL,
    `emergencyBeds` INTEGER NULL,
    `physicalTherapyBeds` INTEGER NULL,
    `psychClosedUpper` INTEGER NULL,
    `psychClosedNormal` INTEGER NULL,
    `psychOpenUpper` INTEGER NULL,
    `psychOpenNormal` INTEGER NULL,
    `isolationBeds` INTEGER NULL,
    `sterileBeds` INTEGER NULL,
    `nurseGrade` VARCHAR(10) NULL,
    `specialtyField` VARCHAR(100) NULL,

    UNIQUE INDEX `Hospital_sourceId_key`(`sourceId`),
    INDEX `Hospital_city_district_idx`(`city`, `district`),
    INDEX `Hospital_lat_lng_idx`(`lat`, `lng`),
    INDEX `Hospital_bjdCode_idx`(`bjdCode`),
    INDEX `Hospital_viewCount_idx`(`viewCount`),
    INDEX `Hospital_name_idx`(`name`),
    FULLTEXT INDEX `Hospital_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HospitalDepartment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `hospitalId` VARCHAR(50) NOT NULL,
    `dgsbjtCdNm` VARCHAR(100) NOT NULL,
    `dgsbjtPrSdrCnt` INTEGER NULL,

    INDEX `HospitalDepartment_hospitalId_idx`(`hospitalId`),
    UNIQUE INDEX `HospitalDepartment_hospitalId_dgsbjtCdNm_key`(`hospitalId`, `dgsbjtCdNm`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `HospitalEquipment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `hospitalId` VARCHAR(50) NOT NULL,
    `eqpCd` VARCHAR(20) NOT NULL,
    `eqpCdNm` VARCHAR(100) NOT NULL,
    `eqpCnt` INTEGER NULL,

    INDEX `HospitalEquipment_hospitalId_idx`(`hospitalId`),
    UNIQUE INDEX `HospitalEquipment_hospitalId_eqpCd_key`(`hospitalId`, `eqpCd`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Pharmacy` (
    `id` VARCHAR(50) NOT NULL,
    `name` VARCHAR(200) NOT NULL,
    `address` VARCHAR(500) NULL,
    `roadAddress` VARCHAR(500) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `sourceUrl` VARCHAR(500) NULL,
    `viewCount` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `phone` VARCHAR(50) NULL,
    `dutyTel3` VARCHAR(50) NULL,
    `hpid` VARCHAR(100) NOT NULL,
    `postCdn1` VARCHAR(20) NULL,
    `postCdn2` VARCHAR(20) NULL,
    `dutyTime1s` VARCHAR(10) NULL,
    `dutyTime1c` VARCHAR(10) NULL,
    `dutyTime2s` VARCHAR(10) NULL,
    `dutyTime2c` VARCHAR(10) NULL,
    `dutyTime3s` VARCHAR(10) NULL,
    `dutyTime3c` VARCHAR(10) NULL,
    `dutyTime4s` VARCHAR(10) NULL,
    `dutyTime4c` VARCHAR(10) NULL,
    `dutyTime5s` VARCHAR(10) NULL,
    `dutyTime5c` VARCHAR(10) NULL,
    `dutyTime6s` VARCHAR(10) NULL,
    `dutyTime6c` VARCHAR(10) NULL,
    `dutyTime7s` VARCHAR(10) NULL,
    `dutyTime7c` VARCHAR(10) NULL,
    `dutyTime8s` VARCHAR(10) NULL,
    `dutyTime8c` VARCHAR(10) NULL,
    `dutyMapimg` TEXT NULL,
    `dutyInf` TEXT NULL,
    `dutyEtc` TEXT NULL,
    `dataDate` VARCHAR(20) NULL,
    `ykiho` VARCHAR(100) NULL,
    `pharmacistCnt` INTEGER NULL,
    `lunchWeek` VARCHAR(200) NULL,
    `lunchSat` VARCHAR(200) NULL,
    `noTrmtSun` VARCHAR(200) NULL,
    `noTrmtHoli` VARCHAR(200) NULL,
    `recpWeek` VARCHAR(200) NULL,
    `recpSat` VARCHAR(200) NULL,
    `detailSyncedAt` DATETIME(3) NULL,

    UNIQUE INDEX `Pharmacy_sourceId_key`(`sourceId`),
    INDEX `Pharmacy_city_district_idx`(`city`, `district`),
    INDEX `Pharmacy_lat_lng_idx`(`lat`, `lng`),
    INDEX `Pharmacy_bjdCode_idx`(`bjdCode`),
    INDEX `Pharmacy_hpid_idx`(`hpid`),
    INDEX `Pharmacy_ykiho_idx`(`ykiho`),
    INDEX `Pharmacy_viewCount_idx`(`viewCount`),
    INDEX `Pharmacy_name_idx`(`name`),
    FULLTEXT INDEX `Pharmacy_name_address_roadAddress_idx`(`name`, `address`, `roadAddress`) WITH PARSER ngram,
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AptSaleTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `aptDong` VARCHAR(50) NULL,
    `buildYear` INTEGER NULL,
    `floor` INTEGER NULL,
    `exclusiveArea` DECIMAL(10, 2) NULL,
    `jibun` VARCHAR(20) NULL,
    `roadName` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `dealAmount` BIGINT NOT NULL,
    `dealType` VARCHAR(20) NULL,
    `cancelDealDay` VARCHAR(10) NULL,
    `cancelDealType` VARCHAR(20) NULL,
    `buyerType` VARCHAR(10) NULL,
    `sellerType` VARCHAR(10) NULL,
    `registrationDate` VARCHAR(20) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geocodedAt` DATETIME(3) NULL,

    UNIQUE INDEX `AptSaleTransaction_sourceId_key`(`sourceId`),
    INDEX `AptSaleTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `AptSaleTransaction_bjdCode_buildingName_idx`(`bjdCode`, `buildingName`),
    INDEX `AptSaleTransaction_bjdCode_exclusiveArea_idx`(`bjdCode`, `exclusiveArea`),
    INDEX `AptSaleTransaction_buildingName_bjdCode_dealYear_dealMonth_d_idx`(`buildingName`, `bjdCode`, `dealYear`, `dealMonth`, `dealDay`),
    INDEX `AptSaleTransaction_city_district_idx`(`city`, `district`),
    INDEX `AptSaleTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `AptSaleTransaction_city_district_dealYear_dealMonth_idx`(`city`, `district`, `dealYear`, `dealMonth`),
    INDEX `AptSaleTransaction_city_district_buildingName_bjdCode_idx`(`city`, `district`, `buildingName`, `bjdCode`),
    INDEX `AptSaleTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VillaSaleTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `houseType` VARCHAR(20) NULL,
    `buildYear` INTEGER NULL,
    `floor` INTEGER NULL,
    `exclusiveArea` DECIMAL(10, 2) NULL,
    `jibun` VARCHAR(20) NULL,
    `roadName` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `dealAmount` BIGINT NOT NULL,
    `dealType` VARCHAR(20) NULL,
    `cancelDealDay` VARCHAR(10) NULL,
    `cancelDealType` VARCHAR(20) NULL,
    `buyerType` VARCHAR(10) NULL,
    `sellerType` VARCHAR(10) NULL,
    `registrationDate` VARCHAR(20) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geocodedAt` DATETIME(3) NULL,

    UNIQUE INDEX `VillaSaleTransaction_sourceId_key`(`sourceId`),
    INDEX `VillaSaleTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `VillaSaleTransaction_bjdCode_buildingName_idx`(`bjdCode`, `buildingName`),
    INDEX `VillaSaleTransaction_bjdCode_exclusiveArea_idx`(`bjdCode`, `exclusiveArea`),
    INDEX `VillaSaleTransaction_buildingName_bjdCode_dealYear_dealMonth_idx`(`buildingName`, `bjdCode`, `dealYear`, `dealMonth`, `dealDay`),
    INDEX `VillaSaleTransaction_city_district_idx`(`city`, `district`),
    INDEX `VillaSaleTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `VillaSaleTransaction_city_district_dealYear_dealMonth_idx`(`city`, `district`, `dealYear`, `dealMonth`),
    INDEX `VillaSaleTransaction_city_district_buildingName_bjdCode_idx`(`city`, `district`, `buildingName`, `bjdCode`),
    INDEX `VillaSaleTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OffitelSaleTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `buildYear` INTEGER NULL,
    `floor` INTEGER NULL,
    `exclusiveArea` DECIMAL(10, 2) NULL,
    `jibun` VARCHAR(20) NULL,
    `roadName` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `dealAmount` BIGINT NOT NULL,
    `dealType` VARCHAR(20) NULL,
    `cancelDealDay` VARCHAR(10) NULL,
    `cancelDealType` VARCHAR(20) NULL,
    `buyerType` VARCHAR(10) NULL,
    `sellerType` VARCHAR(10) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geocodedAt` DATETIME(3) NULL,

    UNIQUE INDEX `OffitelSaleTransaction_sourceId_key`(`sourceId`),
    INDEX `OffitelSaleTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `OffitelSaleTransaction_bjdCode_buildingName_idx`(`bjdCode`, `buildingName`),
    INDEX `OffitelSaleTransaction_bjdCode_exclusiveArea_idx`(`bjdCode`, `exclusiveArea`),
    INDEX `OffitelSaleTransaction_buildingName_bjdCode_dealYear_dealMon_idx`(`buildingName`, `bjdCode`, `dealYear`, `dealMonth`, `dealDay`),
    INDEX `OffitelSaleTransaction_city_district_idx`(`city`, `district`),
    INDEX `OffitelSaleTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `OffitelSaleTransaction_city_district_dealYear_dealMonth_idx`(`city`, `district`, `dealYear`, `dealMonth`),
    INDEX `OffitelSaleTransaction_city_district_buildingName_bjdCode_idx`(`city`, `district`, `buildingName`, `bjdCode`),
    INDEX `OffitelSaleTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LandSaleTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `jibun` VARCHAR(20) NULL,
    `jimok` VARCHAR(20) NULL,
    `landUse` VARCHAR(50) NULL,
    `dealArea` DECIMAL(12, 2) NULL,
    `shareDeal` BOOLEAN NOT NULL DEFAULT false,
    `dealAmount` BIGINT NOT NULL,
    `dealType` VARCHAR(20) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `cancelDealDay` VARCHAR(10) NULL,
    `cancelDealType` VARCHAR(20) NULL,
    `sourceId` VARCHAR(200) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `LandSaleTransaction_sourceId_key`(`sourceId`),
    INDEX `LandSaleTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `LandSaleTransaction_bjdCode_dongName_dealYear_dealMonth_idx`(`bjdCode`, `dongName`, `dealYear`, `dealMonth`),
    INDEX `LandSaleTransaction_city_district_idx`(`city`, `district`),
    INDEX `LandSaleTransaction_jimok_idx`(`jimok`),
    INDEX `LandSaleTransaction_landUse_idx`(`landUse`),
    INDEX `LandSaleTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `LandSaleTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `LandAreaSummary` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `transactionCount` INTEGER NOT NULL DEFAULT 0,
    `recentCount` INTEGER NOT NULL DEFAULT 0,
    `avgPricePerPyeong` DECIMAL(14, 2) NULL,
    `daeCount` INTEGER NOT NULL DEFAULT 0,
    `daeNonShareCount` INTEGER NOT NULL DEFAULT 0,
    `latestDealDate` DATETIME(3) NULL,
    `jimokBreakdown` JSON NOT NULL,
    `isIndexable` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `LandAreaSummary_city_district_transactionCount_idx`(`city`, `district`, `transactionCount`),
    INDEX `LandAreaSummary_isIndexable_idx`(`isIndexable`),
    UNIQUE INDEX `LandAreaSummary_bjdCode_dongName_key`(`bjdCode`, `dongName`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AptRentTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `buildYear` INTEGER NULL,
    `floor` INTEGER NULL,
    `exclusiveArea` DECIMAL(10, 2) NULL,
    `jibun` VARCHAR(20) NULL,
    `roadName` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `rentType` VARCHAR(10) NOT NULL,
    `deposit` BIGINT NOT NULL,
    `monthlyRent` INTEGER NULL,
    `contractTerm` VARCHAR(30) NULL,
    `contractType` VARCHAR(10) NULL,
    `preDeposit` BIGINT NULL,
    `preMonthlyRent` INTEGER NULL,
    `useRenewalRight` VARCHAR(10) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geocodedAt` DATETIME(3) NULL,

    UNIQUE INDEX `AptRentTransaction_sourceId_key`(`sourceId`),
    INDEX `AptRentTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `AptRentTransaction_bjdCode_buildingName_idx`(`bjdCode`, `buildingName`),
    INDEX `AptRentTransaction_bjdCode_exclusiveArea_idx`(`bjdCode`, `exclusiveArea`),
    INDEX `AptRentTransaction_buildingName_bjdCode_dealYear_dealMonth_d_idx`(`buildingName`, `bjdCode`, `dealYear`, `dealMonth`, `dealDay`),
    INDEX `AptRentTransaction_city_district_idx`(`city`, `district`),
    INDEX `AptRentTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `AptRentTransaction_city_district_dealYear_dealMonth_idx`(`city`, `district`, `dealYear`, `dealMonth`),
    INDEX `AptRentTransaction_city_district_buildingName_bjdCode_idx`(`city`, `district`, `buildingName`, `bjdCode`),
    INDEX `AptRentTransaction_rentType_idx`(`rentType`),
    INDEX `AptRentTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `VillaRentTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `houseType` VARCHAR(20) NULL,
    `buildYear` INTEGER NULL,
    `floor` INTEGER NULL,
    `exclusiveArea` DECIMAL(10, 2) NULL,
    `jibun` VARCHAR(20) NULL,
    `roadName` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `rentType` VARCHAR(10) NOT NULL,
    `deposit` BIGINT NOT NULL,
    `monthlyRent` INTEGER NULL,
    `contractTerm` VARCHAR(30) NULL,
    `contractType` VARCHAR(10) NULL,
    `preDeposit` BIGINT NULL,
    `preMonthlyRent` INTEGER NULL,
    `useRenewalRight` VARCHAR(10) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geocodedAt` DATETIME(3) NULL,

    UNIQUE INDEX `VillaRentTransaction_sourceId_key`(`sourceId`),
    INDEX `VillaRentTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `VillaRentTransaction_bjdCode_buildingName_idx`(`bjdCode`, `buildingName`),
    INDEX `VillaRentTransaction_bjdCode_exclusiveArea_idx`(`bjdCode`, `exclusiveArea`),
    INDEX `VillaRentTransaction_buildingName_bjdCode_dealYear_dealMonth_idx`(`buildingName`, `bjdCode`, `dealYear`, `dealMonth`, `dealDay`),
    INDEX `VillaRentTransaction_city_district_idx`(`city`, `district`),
    INDEX `VillaRentTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `VillaRentTransaction_city_district_dealYear_dealMonth_idx`(`city`, `district`, `dealYear`, `dealMonth`),
    INDEX `VillaRentTransaction_city_district_buildingName_bjdCode_idx`(`city`, `district`, `buildingName`, `bjdCode`),
    INDEX `VillaRentTransaction_rentType_idx`(`rentType`),
    INDEX `VillaRentTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `OffitelRentTransaction` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `buildYear` INTEGER NULL,
    `floor` INTEGER NULL,
    `exclusiveArea` DECIMAL(10, 2) NULL,
    `jibun` VARCHAR(20) NULL,
    `roadName` VARCHAR(100) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `dealYear` INTEGER NOT NULL,
    `dealMonth` INTEGER NOT NULL,
    `dealDay` INTEGER NULL,
    `rentType` VARCHAR(10) NOT NULL,
    `deposit` BIGINT NOT NULL,
    `monthlyRent` INTEGER NULL,
    `contractTerm` VARCHAR(30) NULL,
    `contractType` VARCHAR(10) NULL,
    `preDeposit` BIGINT NULL,
    `preMonthlyRent` INTEGER NULL,
    `useRenewalRight` VARCHAR(10) NULL,
    `sourceId` VARCHAR(100) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `geocodedAt` DATETIME(3) NULL,

    UNIQUE INDEX `OffitelRentTransaction_sourceId_key`(`sourceId`),
    INDEX `OffitelRentTransaction_bjdCode_dealYear_dealMonth_idx`(`bjdCode`, `dealYear`, `dealMonth`),
    INDEX `OffitelRentTransaction_bjdCode_buildingName_idx`(`bjdCode`, `buildingName`),
    INDEX `OffitelRentTransaction_bjdCode_exclusiveArea_idx`(`bjdCode`, `exclusiveArea`),
    INDEX `OffitelRentTransaction_buildingName_bjdCode_dealYear_dealMon_idx`(`buildingName`, `bjdCode`, `dealYear`, `dealMonth`, `dealDay`),
    INDEX `OffitelRentTransaction_city_district_idx`(`city`, `district`),
    INDEX `OffitelRentTransaction_dealYear_dealMonth_idx`(`dealYear`, `dealMonth`),
    INDEX `OffitelRentTransaction_city_district_dealYear_dealMonth_idx`(`city`, `district`, `dealYear`, `dealMonth`),
    INDEX `OffitelRentTransaction_city_district_buildingName_bjdCode_idx`(`city`, `district`, `buildingName`, `bjdCode`),
    INDEX `OffitelRentTransaction_rentType_idx`(`rentType`),
    INDEX `OffitelRentTransaction_syncedAt_idx`(`syncedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RealEstateBuildingSummary` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(20) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `latestPrice` BIGINT NULL,
    `latestDealYear` INTEGER NULL,
    `latestDealMonth` INTEGER NULL,
    `latestDealDay` INTEGER NULL,
    `buildYear` INTEGER NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `transactionCount` INTEGER NOT NULL DEFAULT 0,
    `monthlyRent` INTEGER NULL,
    `jeonseDeposit` INTEGER NULL,
    `jeonseDealKey` INTEGER NULL,
    `wolseDeposit` INTEGER NULL,
    `wolseMonthlyRent` INTEGER NULL,
    `wolseDealKey` INTEGER NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `RealEstateBuildingSummary_type_transactionCount_idx`(`type`, `transactionCount`),
    INDEX `RealEstateBuildingSummary_type_city_district_transactionCoun_idx`(`type`, `city`, `district`, `transactionCount`),
    INDEX `RealEstateBuildingSummary_type_buildingName_idx`(`type`, `buildingName`),
    INDEX `RealEstateBuildingSummary_type_bjdCode_latestDealYear_latest_idx`(`type`, `bjdCode`, `latestDealYear`, `latestDealMonth`, `transactionCount`),
    INDEX `RealEstateBuildingSummary_type_lat_lng_idx`(`type`, `lat`, `lng`),
    UNIQUE INDEX `RealEstateBuildingSummary_type_buildingName_bjdCode_key`(`type`, `buildingName`, `bjdCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RealEstateBuildingSummaryV2` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `type` VARCHAR(20) NOT NULL,
    `buildingKey` CHAR(64) NOT NULL,
    `buildingName` VARCHAR(200) NOT NULL,
    `bjdCode` VARCHAR(10) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `dongName` VARCHAR(50) NOT NULL,
    `jibun` VARCHAR(20) NULL,
    `latestPrice` BIGINT NULL,
    `latestDealYear` INTEGER NULL,
    `latestDealMonth` INTEGER NULL,
    `latestDealDay` INTEGER NULL,
    `buildYear` INTEGER NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `transactionCount` INTEGER NOT NULL DEFAULT 0,
    `monthlyRent` INTEGER NULL,
    `jeonseDeposit` INTEGER NULL,
    `jeonseDealKey` INTEGER NULL,
    `wolseDeposit` INTEGER NULL,
    `wolseMonthlyRent` INTEGER NULL,
    `wolseDealKey` INTEGER NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `RealEstateBuildingSummaryV2_type_transactionCount_idx`(`type`, `transactionCount`),
    INDEX `RealEstateBuildingSummaryV2_type_city_district_transactionCo_idx`(`type`, `city`, `district`, `transactionCount`),
    INDEX `RealEstateBuildingSummaryV2_type_buildingName_idx`(`type`, `buildingName`),
    INDEX `RealEstateBuildingSummaryV2_type_bjdCode_latestDealYear_late_idx`(`type`, `bjdCode`, `latestDealYear`, `latestDealMonth`, `transactionCount`),
    INDEX `RealEstateBuildingSummaryV2_type_lat_lng_idx`(`type`, `lat`, `lng`),
    UNIQUE INDEX `RealEstateBuildingSummaryV2_type_buildingKey_key`(`type`, `buildingKey`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RealEstateSummaryState` (
    `id` INTEGER NOT NULL,
    `status` VARCHAR(20) NOT NULL,
    `runId` VARCHAR(64) NOT NULL,
    `sourceFingerprint` CHAR(64) NOT NULL,
    `report` JSON NOT NULL,
    `validatedAt` DATETIME(3) NULL,
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Subscription` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `houseManageNo` VARCHAR(20) NOT NULL,
    `pblancNo` VARCHAR(20) NOT NULL,
    `sourceType` VARCHAR(20) NOT NULL DEFAULT 'APT',
    `houseName` VARCHAR(200) NOT NULL,
    `houseType` VARCHAR(20) NOT NULL,
    `houseDetailType` VARCHAR(20) NULL,
    `rentType` VARCHAR(20) NULL,
    `publicRentType` VARCHAR(20) NULL,
    `publicRental` JSON NULL,
    `supersededById` INTEGER NULL,
    `regionName` VARCHAR(100) NOT NULL,
    `supplyLocation` VARCHAR(500) NULL,
    `supplyZipCode` VARCHAR(10) NULL,
    `totalSupplyCount` INTEGER NULL,
    `announcementDate` DATETIME(3) NULL,
    `receptionStartDate` DATETIME(3) NULL,
    `receptionEndDate` DATETIME(3) NULL,
    `specialStartDate` DATETIME(3) NULL,
    `specialEndDate` DATETIME(3) NULL,
    `rank1AreaStartDate` DATETIME(3) NULL,
    `rank1AreaEndDate` DATETIME(3) NULL,
    `rank1OtherStartDate` DATETIME(3) NULL,
    `rank1OtherEndDate` DATETIME(3) NULL,
    `rank2AreaStartDate` DATETIME(3) NULL,
    `rank2AreaEndDate` DATETIME(3) NULL,
    `rank2OtherStartDate` DATETIME(3) NULL,
    `rank2OtherEndDate` DATETIME(3) NULL,
    `winnerDate` DATETIME(3) NULL,
    `contractStartDate` DATETIME(3) NULL,
    `contractEndDate` DATETIME(3) NULL,
    `moveInMonth` VARCHAR(10) NULL,
    `constructorName` VARCHAR(200) NULL,
    `developerName` VARCHAR(200) NULL,
    `homepage` VARCHAR(500) NULL,
    `pblancUrl` VARCHAR(500) NULL,
    `inquiryTel` VARCHAR(50) NULL,
    `status` VARCHAR(20) NOT NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `geocodedAt` DATETIME(3) NULL,
    `geocodeAttempts` INTEGER NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `Subscription_sourceType_status_idx`(`sourceType`, `status`),
    INDEX `Subscription_status_idx`(`status`),
    INDEX `Subscription_announcementDate_idx`(`announcementDate`),
    INDEX `Subscription_regionName_idx`(`regionName`),
    INDEX `Subscription_supersededById_idx`(`supersededById`),
    UNIQUE INDEX `Subscription_houseManageNo_pblancNo_sourceType_key`(`houseManageNo`, `pblancNo`, `sourceType`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SubscriptionUnitType` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `subscriptionId` INTEGER NOT NULL,
    `modelNo` VARCHAR(10) NOT NULL,
    `houseType` VARCHAR(30) NULL,
    `supplyArea` VARCHAR(20) NULL,
    `generalCount` INTEGER NULL,
    `specialCount` INTEGER NULL,
    `topAmount` INTEGER NULL,
    `newlywedsCount` INTEGER NULL,
    `multiChildCount` INTEGER NULL,
    `firstLifeCount` INTEGER NULL,
    `elderlyCount` INTEGER NULL,
    `institutionCount` INTEGER NULL,
    `youthCount` INTEGER NULL,
    `newbornCount` INTEGER NULL,
    `transferCount` INTEGER NULL,
    `etcCount` INTEGER NULL,

    INDEX `SubscriptionUnitType_subscriptionId_idx`(`subscriptionId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SubscriptionCompetition` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `subscriptionId` INTEGER NOT NULL,
    `modelNo` VARCHAR(10) NOT NULL,
    `houseType` VARCHAR(30) NULL,
    `rank` INTEGER NOT NULL,
    `regionCode` VARCHAR(5) NOT NULL,
    `regionName` VARCHAR(20) NULL,
    `supplyCount` INTEGER NULL,
    `applicantCount` INTEGER NULL,
    `competitionRate` VARCHAR(30) NULL,

    INDEX `SubscriptionCompetition_subscriptionId_idx`(`subscriptionId`),
    UNIQUE INDEX `SubscriptionCompetition_subscriptionId_modelNo_rank_regionCo_key`(`subscriptionId`, `modelNo`, `rank`, `regionCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SubscriptionScore` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `subscriptionId` INTEGER NOT NULL,
    `modelNo` VARCHAR(10) NOT NULL,
    `houseType` VARCHAR(30) NULL,
    `regionCode` VARCHAR(5) NOT NULL,
    `regionName` VARCHAR(20) NULL,
    `minScore` VARCHAR(10) NULL,
    `maxScore` VARCHAR(10) NULL,
    `avgScore` VARCHAR(10) NULL,

    INDEX `SubscriptionScore_subscriptionId_idx`(`subscriptionId`),
    UNIQUE INDEX `SubscriptionScore_subscriptionId_modelNo_regionCode_key`(`subscriptionId`, `modelNo`, `regionCode`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `SubscriptionSpecialStatus` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `subscriptionId` INTEGER NOT NULL,
    `houseType` VARCHAR(30) NULL,
    `resultName` VARCHAR(50) NULL,
    `specialSupplyCount` INTEGER NULL,
    `newlywedsSupply` INTEGER NULL,
    `multiChildSupply` INTEGER NULL,
    `firstLifeSupply` INTEGER NULL,
    `elderlySupply` INTEGER NULL,
    `institutionSupply` INTEGER NULL,
    `youthSupply` INTEGER NULL,
    `newbornSupply` INTEGER NULL,
    `transferSupply` INTEGER NULL,
    `newlywedsAreaCount` INTEGER NULL,
    `multiChildAreaCount` INTEGER NULL,
    `firstLifeAreaCount` INTEGER NULL,
    `elderlyAreaCount` INTEGER NULL,
    `youthAreaCount` INTEGER NULL,
    `newbornAreaCount` INTEGER NULL,
    `newlywedsOtherCount` INTEGER NULL,
    `multiChildOtherCount` INTEGER NULL,
    `firstLifeOtherCount` INTEGER NULL,
    `elderlyOtherCount` INTEGER NULL,
    `youthOtherCount` INTEGER NULL,
    `newbornOtherCount` INTEGER NULL,
    `institutionDecisionCount` INTEGER NULL,
    `institutionPrepareCount` INTEGER NULL,
    `transferCount` INTEGER NULL,

    INDEX `SubscriptionSpecialStatus_subscriptionId_idx`(`subscriptionId`),
    UNIQUE INDEX `SubscriptionSpecialStatus_subscriptionId_houseType_key`(`subscriptionId`, `houseType`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FacilityNaverBlogCache` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `category` VARCHAR(20) NOT NULL,
    `facilityId` VARCHAR(100) NOT NULL,
    `query` VARCHAR(300) NOT NULL,
    `posts` JSON NOT NULL,
    `itemCount` INTEGER NOT NULL DEFAULT 0,
    `fetchedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NOT NULL,

    INDEX `FacilityNaverBlogCache_expiresAt_idx`(`expiresAt`),
    UNIQUE INDEX `FacilityNaverBlogCache_category_facilityId_key`(`category`, `facilityId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `RealEstateNaverBlogCache` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `realEstateType` VARCHAR(20) NOT NULL,
    `buildingKey` VARCHAR(200) NOT NULL,
    `query` VARCHAR(300) NOT NULL,
    `posts` JSON NOT NULL,
    `itemCount` INTEGER NOT NULL DEFAULT 0,
    `fetchedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `expiresAt` DATETIME(3) NOT NULL,

    INDEX `RealEstateNaverBlogCache_expiresAt_idx`(`expiresAt`),
    UNIQUE INDEX `RealEstateNaverBlogCache_realEstateType_buildingKey_key`(`realEstateType`, `buildingKey`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AuctionItem` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `cltrMngNo` VARCHAR(50) NOT NULL,
    `pbctCdtnNo` VARCHAR(50) NOT NULL,
    `plnmNo` VARCHAR(50) NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `bjdCode` VARCHAR(5) NOT NULL,
    `dongName` VARCHAR(50) NULL,
    `address` VARCHAR(500) NOT NULL,
    `usage` VARCHAR(100) NULL,
    `usageGroup` VARCHAR(20) NOT NULL,
    `propertyType` VARCHAR(50) NULL,
    `dpslMtdNm` VARCHAR(20) NULL,
    `bidMethod` VARCHAR(40) NULL,
    `competitionMethod` VARCHAR(40) NULL,
    `bidType` VARCHAR(40) NULL,
    `evictionResp` VARCHAR(40) NULL,
    `isShare` BOOLEAN NOT NULL DEFAULT false,
    `thumbnailUrl` VARCHAR(500) NULL,
    `landArea` DECIMAL(12, 2) NULL,
    `bldArea` DECIMAL(12, 2) NULL,
    `apslAssAmt` BIGINT NULL,
    `minBidPrc` BIGINT NULL,
    `failCnt` INTEGER NOT NULL DEFAULT 0,
    `bidRound` INTEGER NULL,
    `bidBeginDtm` DATETIME(3) NULL,
    `bidCloseDtm` DATETIME(3) NULL,
    `orgNm` VARCHAR(100) NULL,
    `pvctTrgtYn` BOOLEAN NOT NULL DEFAULT false,
    `status` VARCHAR(20) NOT NULL,
    `isClosed` BOOLEAN NOT NULL DEFAULT false,
    `resultType` VARCHAR(20) NULL,
    `winBidPrc` BIGINT NULL,
    `bidRate` DECIMAL(6, 2) NULL,
    `resultDate` DATETIME(3) NULL,
    `lat` DECIMAL(10, 7) NULL,
    `lng` DECIMAL(10, 7) NULL,
    `geocodedAt` DATETIME(3) NULL,
    `sourceId` VARCHAR(200) NOT NULL,
    `firstSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `lastSeenAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `syncedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `AuctionItem_cltrMngNo_key`(`cltrMngNo`),
    UNIQUE INDEX `AuctionItem_sourceId_key`(`sourceId`),
    INDEX `AuctionItem_bjdCode_usageGroup_status_idx`(`bjdCode`, `usageGroup`, `status`),
    INDEX `AuctionItem_city_district_idx`(`city`, `district`),
    INDEX `AuctionItem_status_isClosed_idx`(`status`, `isClosed`),
    INDEX `AuctionItem_bidCloseDtm_idx`(`bidCloseDtm`),
    INDEX `AuctionItem_isClosed_lastSeenAt_idx`(`isClosed`, `lastSeenAt`),
    INDEX `AuctionItem_resultDate_idx`(`resultDate`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AuctionAreaSummary` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bjdCode` VARCHAR(5) NOT NULL,
    `usageGroup` VARCHAR(20) NOT NULL,
    `city` VARCHAR(50) NOT NULL,
    `district` VARCHAR(50) NOT NULL,
    `activeCount` INTEGER NOT NULL DEFAULT 0,
    `closedCount` INTEGER NOT NULL DEFAULT 0,
    `soldCount` INTEGER NOT NULL DEFAULT 0,
    `avgBidRate` DECIMAL(6, 2) NULL,
    `avgApslAmt` BIGINT NULL,
    `avgWinBidPrc` BIGINT NULL,
    `failRate` DECIMAL(5, 2) NULL,
    `latestResultDate` DATETIME(3) NULL,
    `isIndexable` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    INDEX `AuctionAreaSummary_city_district_idx`(`city`, `district`),
    INDEX `AuctionAreaSummary_usageGroup_avgBidRate_idx`(`usageGroup`, `avgBidRate`),
    INDEX `AuctionAreaSummary_isIndexable_idx`(`isIndexable`),
    UNIQUE INDEX `AuctionAreaSummary_bjdCode_usageGroup_key`(`bjdCode`, `usageGroup`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `FacilityGone` (
    `id` VARCHAR(64) NOT NULL,
    `category` VARCHAR(32) NOT NULL,
    `reason` VARCHAR(64) NULL,
    `goneAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    INDEX `FacilityGone_category_idx`(`category`),
    INDEX `FacilityGone_goneAt_idx`(`goneAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `SchoolEnrollment` ADD CONSTRAINT `SchoolEnrollment_schoolId_fkey` FOREIGN KEY (`schoolId`) REFERENCES `School`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SchoolDepartment` ADD CONSTRAINT `SchoolDepartment_schoolId_fkey` FOREIGN KEY (`schoolId`) REFERENCES `School`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HospitalDepartment` ADD CONSTRAINT `HospitalDepartment_hospitalId_fkey` FOREIGN KEY (`hospitalId`) REFERENCES `Hospital`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `HospitalEquipment` ADD CONSTRAINT `HospitalEquipment_hospitalId_fkey` FOREIGN KEY (`hospitalId`) REFERENCES `Hospital`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionUnitType` ADD CONSTRAINT `SubscriptionUnitType_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `Subscription`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionCompetition` ADD CONSTRAINT `SubscriptionCompetition_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `Subscription`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionScore` ADD CONSTRAINT `SubscriptionScore_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `Subscription`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `SubscriptionSpecialStatus` ADD CONSTRAINT `SubscriptionSpecialStatus_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `Subscription`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

