import { readFileSync, renameSync, writeFileSync } from 'node:fs'
import { pathToFileURL } from 'node:url'

const ROOT = '/home/project2'

export function fixedRuntime(sha, readiness) {
  if (!/^[0-9a-f]{40}$/.test(sha)) throw new Error('expected tested 40-character commit SHA')
  if (!readiness?.ready || !readiness.db?.ok || readiness.summary?.mode !== 'address' ||
      !/^[0-9a-f-]{36}$/.test(readiness.summary?.runId ?? '') ||
      readiness.realEstateUrls?.mode !== 'preserved' || !readiness.realEstateUrls.ready ||
      !readiness.releaseId) {
    throw new Error('active backend is not ready in address/preserved mode')
  }

  const id = `fixed-${sha.slice(0, 12)}`
  const common = {
    NODE_ENV: 'production',
    ILSK_RELEASE_ID: id,
    SITEMAP_DIR: `${ROOT}/sitemaps`,
  }
  return {
    id,
    previousId: readiness.releaseId,
    summaryRunId: readiness.summary.runId,
    backend: {
      ...common,
      PORT: '8000',
      HOST: '127.0.0.1',
      REAL_ESTATE_SUMMARY_MODE: 'address',
      REAL_ESTATE_URL_MODE: 'preserved',
      REAL_ESTATE_SUMMARY_RUN_ID: readiness.summary.runId,
      ILSK_SUMMARY_RUN_ID: readiness.summary.runId,
      REAL_ESTATE_WRITE_LOCK_DIR: `${ROOT}/run/real-estate-locks`,
      SITEMAP_REGEN_BASE: 'http://127.0.0.1:3000',
    },
    frontend: {
      ...common,
      PORT: '3000',
      NUXT_PORT: '3000',
      HOST: '127.0.0.1',
      NITRO_HOST: '127.0.0.1',
      NUXT_INTERNAL_API_BASE: 'http://127.0.0.1:8000',
      NUXT_PUBLIC_API_BASE: '',
    },
  }
}

export function updateEnvText(original, assignments) {
  const keys = new Set(Object.keys(assignments))
  for (const [key, value] of Object.entries(assignments)) {
    if (!/^[A-Z][A-Z0-9_]*$/.test(key) || !/^[\x20-\x7e]*$/.test(value) || /[\r\n]/.test(value)) {
      throw new Error(`invalid generated env entry: ${key}`)
    }
  }
  const retained = original.split(/\r?\n/).filter(line => {
    const match = /^\s*([A-Z][A-Z0-9_]*)=/.exec(line)
    return !match || !keys.has(match[1])
  })
  while (retained.at(-1) === '') retained.pop()
  return `${retained.join('\n')}\n${Object.entries(assignments).map(([key, value]) => `${key}=${value}`).join('\n')}\n`
}

export function renderFixedNginx(id) {
  if (!/^fixed-[0-9a-f]{12}$/.test(id)) throw new Error('invalid fixed deployment id')
  return `# Fixed-path ilsangkit deployment. Generated by GitHub Actions.\n` +
    `upstream ilsangkit_release_web { server 127.0.0.1:3000; }\n` +
    `upstream ilsangkit_release_api { server 127.0.0.1:8000; }\n` +
    `map $host $ilsangkit_release { default "${id}"; }\n`
}

export function selectReleaseProcesses(processes) {
  if (!Array.isArray(processes)) throw new Error('expected PM2 process list')
  const names = []
  for (const process of processes) {
    const match = /^ilsangkit-(backend|frontend)-([a-z0-9-]+)$/.exec(process?.name ?? '')
    if (!match) continue
    const expected = `${ROOT}/deploy/releases/${match[2]}/${match[1]}`
    if (process.pm2_env?.pm_cwd !== expected) {
      throw new Error(`unexpected release process directory: ${process.name}`)
    }
    names.push(process.name)
  }
  return names
}

export function firstHashedAsset(html) {
  const path = html.match(/\/_nuxt\/[A-Za-z0-9_./-]+\.(?:css|js)\b/)?.[0]
  if (!path || path.split('/').includes('..')) throw new Error('no safe hashed Nuxt asset in SSR HTML')
  return path
}

function replaceFile(path, content, mode) {
  const temporary = `${path}.${process.pid}.tmp`
  writeFileSync(temporary, content, { mode })
  renameSync(temporary, path)
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    const [command, sha, readinessPath, backendEnvPath, frontendEnvPath] = process.argv.slice(2)
    if (command === 'render-nginx') {
      if (!sha || !readinessPath) throw new Error('usage: fixed-runtime.mjs render-nginx <fixed-id> <output>')
      replaceFile(readinessPath, renderFixedNginx(sha), 0o644)
      process.exit(0)
    }
    if (command === 'select-release-processes') {
      console.log(selectReleaseProcesses(JSON.parse(readFileSync(0, 'utf8'))).join('\n'))
      process.exit(0)
    }
    if (command === 'asset-path') {
      if (!sha) throw new Error('usage: fixed-runtime.mjs asset-path <html-file>')
      console.log(firstHashedAsset(readFileSync(sha, 'utf8')))
      process.exit(0)
    }
    if (command !== 'prepare' || !sha || !readinessPath || !backendEnvPath || !frontendEnvPath) {
      throw new Error('usage: fixed-runtime.mjs prepare <sha> <readiness.json> <backend.env> <frontend.env>')
    }
    const readiness = JSON.parse(readFileSync(readinessPath, 'utf8'))
    const runtime = fixedRuntime(sha, readiness)
    replaceFile(backendEnvPath, updateEnvText(readFileSync(backendEnvPath, 'utf8'), runtime.backend), 0o600)
    replaceFile(frontendEnvPath, updateEnvText(readFileSync(frontendEnvPath, 'utf8'), runtime.frontend), 0o600)
    console.log(JSON.stringify({ id: runtime.id, previousId: runtime.previousId, summaryRunId: runtime.summaryRunId }))
  } catch (error) {
    console.error(`[fixed-runtime] ${error.message}`)
    process.exitCode = 2
  }
}
